1. Crear un DataFrame con los nombres, profesión y países de 8 personas, y luego imprimir el DataFrame.

In [ ]:
#Dataframe con lista nombres, Profesión y Paises.

import pandas as pd
data = {'Nombre': ['Daniel', 'Peter', 'Nikol', 'Linda', 'Oscar', 'Lina', 'Francesca', 'Jhon'],
'Ciudad': ['Colombia', 'USA', 'Francia', 'España', 'Brasil', 'Portugal', 'Francia', 'USA'],
'Profesion': ['Quimico', 'Ingeniero', 'Contadora', 'Arquicteto', 'Cheff', 'Programador', 'Analista', 'Biologo']}
df = pd.DataFrame(data)
df


Nombre    Ciudad    Profesion
0     Daniel  Colombia      Quimico
1      Peter       USA    Ingeniero
2      Nikol   Francia    Contadora
3      Linda    España   Arquicteto
4      Oscar    Brasil        Cheff
5       Lina  Portugal  Programador
6  Francesca   Francia     Analista
7       Jhon       USA      Biologo

2.	Cargar un archivo CSV (puedes usar un archivo de ejemplo en tu entorno) y mostrar las primeras 5 filas.

In [ ]:
#Metodo to_string() importar archivo .csv

import pandas as pd

# Leer el archivo .csv
df = pd.read_csv('/content/drive/MyDrive/Analisis Datos/data.csv')

# Mostrar las primeras 5 filas
df.head(5)

Duracion  Pulso  Maxpulso  Calorias
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0

3.	Generar un DataFrame con 100 filas y 8 columnas de valores aleatorios, y luego mostrar un resumen estadístico de los datos.

In [ ]:
# Data Frame con 100 filas y 8 Columnas, Valores aleatorios con su estadistica

import pandas as pd
import numpy as np

# Crear un DataFrame con 100 filas y 8 columnas de valores aleatorios
df = pd.DataFrame(np.random.rand(100, 8))

# Mostrar un resumen estadístico de los datos
df.describe()









0           1           2           3           4           5  \
count  100.000000  100.000000  100.000000  100.000000  100.000000  100.000000   
mean     0.546168    0.459387    0.494079    0.467664    0.481733    0.519799   
std      0.283189    0.260005    0.286120    0.273802    0.307151    0.297085   
min      0.023516    0.001638    0.007850    0.000233    0.001752    0.000163   
25%      0.282300    0.255510    0.276574    0.235897    0.178031    0.259599   
50%      0.550493    0.455673    0.471570    0.464306    0.508397    0.567341   
75%      0.808462    0.604132    0.720151    0.715627    0.767109    0.774424   
max      0.998229    0.985507    0.997561    0.983365    0.975660    0.972331   

                6           7  
count  100.000000  100.000000  
mean     0.487625    0.491391  
std      0.279461    0.283369  
min      0.007570    0.004540  
25%      0.260874    0.206219  
50%      0.487197    0.558020  
75%      0.709101    0.724368  
max      0.997925    0.956783

1. Crear un array de números del 1 al 10 y mostrar la suma, la media, y el valor máximo.

In [ ]:
import numpy as np

num= np.arange(1,11)
print(num)
suma = num.sum()
print("Suma:",suma)
print("Media:",num.mean())
print("Máximo:",num.max())

[ 1  2  3  4  5  6  7  8  9 10]
Suma: 55
Media: 5.5
Máximo: 10


2. Crear un array de 3x4 lleno de ceros y luego cambiar su forma a 2x6

In [ ]:
import numpy as np
zeros=np.zeros((3,4))  #Creamos la matriz de ceros de 3x4
print(zeros)

print()

arr = zeros.reshape(2,6) #Cambiamos su forma a matriz de 2x6
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


3. Generar una matriz aleatoria de 3x3 y calcular su transpuesta.

In [ ]:
import numpy as np

matrice = np.random.rand(3,3)  # Crear una matriz 3x3 con valores aleatorios
print("Matriz original")
print(matrice)

print()

matrice_transpuesta= matrice.T   # Calcula la matriz transpuesta
print("Matriz Transpuesta")
print(matrice_transpuesta)

Matriz original
[[0.82641476 0.20259599 0.05353949]
 [0.62447594 0.98323914 0.87918419]
 [0.71757163 0.23618979 0.45462853]]

Matriz Transpuesta
[[0.82641476 0.62447594 0.71757163]
 [0.20259599 0.98323914 0.23618979]
 [0.05353949 0.87918419 0.45462853]]


4.	Concatenar dos arrays de NumPy, cada uno con 5 valores, y luego imprimir el array concatenado.

In [ ]:
x = np.random.rand(1,5)
y = np.random.rand(1,5)
print("Array a:",x)
print()
print("Array b:",y)
print()

arr_concatenado = np.concatenate((x,y))
print("Array final:",arr_concatenado)

Array a: [[0.58555441 0.19135483 0.8908152  0.78426214 0.49509882]]

Array b: [[0.02105231 0.80500609 0.26460722 0.83348057 0.24520378]]

Array final: [[0.58555441 0.19135483 0.8908152  0.78426214 0.49509882]
 [0.02105231 0.80500609 0.26460722 0.83348057 0.24520378]]
